repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: dotnet-format
        name: dotnet format
        entry: cmd /c "dotnet format scr/VrKayak.Backend/VrKayak.Backend.csproj --verify-no-changes --include %* > dotnet-format.log 2>&1"
        language: system
        files: \.(cs)$
        pass_filenames: true

#  - repo: local
#    hooks:
#      - id: dotnet-build
#        name: dotnet build
#        entry: cmd /c "dotnet build --no-restore --verbosity quiet > dotnet-build.log 2>&1"
#        language: system
#        files: \.(cs|csproj|sln)$
#        pass_filenames: false
#        always_run: true

  - repo: local
    hooks:
      - id: dotnet-build
        name: dotnet build
        entry: cmd /c "dotnet build scr/VrKayak.Backend/VrKayak.Backend.csproj --no-restore --verbosity quiet > dotnet-build.log 2>&1"
        language: system
        files: \.(cs|csproj)$
        pass_filenames: false
        always_run: true

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: ^(.*\.(csproj|sln|userprefs)|\.gitignore|\.pre-commit-config\.yaml)$
